# Array Creation 

In [38]:
import numpy as np 
from numpy.random import default_rng

In [10]:
array = np.array([[1,2,3,4,5],
                  [1,0,0,0,0],
                  [2,0,0,0,0]])
print(array.shape)

(3, 5)


In [27]:
# 1 Dimension Array
print(np.arange(10))
print(np.arange(0,10,1))
print(np.linspace(1,4,5))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.   1.75 2.5  3.25 4.  ]


In [36]:
# 2 Dimension Array
print(np.eye(3))
print(np.diag([1,2,3,4,5]))
print(np.diag(np.diag([1,2,3,4,5])))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[1 2 3 4 5]


In [43]:
# 3 Dimension Array
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(default_rng(42).random((3,3)))
print(np.indices((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [58]:
a = np.array([1,2,3,4,5])
b = a[:2]
b += 1
print(a)
print(b)

[2 3 3 4 5]
[2 3]


In [83]:
print(np.ones((2,2)))
print(np.eye(2,2))
A = np.ones((2,2))
B = np.eye(2,2)
print(np.stack([A,B]))
print(np.vstack([A,B]))
print(np.hstack([A,B]))
print(np.block([A,B]))

[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 0.]
  [0. 1.]]]
[[1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]


# Array Indexing

In [97]:
x = np.arange(10)
print(x)
x.shape = (2,5)
print(x)
print(x[0])

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


In [111]:
x = np.array([[[1],[2],[3]], 
              [[4],[5],[6]]])
y = np.array([[[1,2,3],[4,5,6]]])
z = x[1:2]
print(z.shape)

(1, 3, 1)


In [120]:
x = np.arange(10)
x.shape = (2,5)
print(x)
print(x[...,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[1 6]


In [149]:
x = np.arange(12)
x.shape = (3,4)
print(x)
print(x.shape)
print(x[:,np.newaxis,:])
print(x[:,np.newaxis,:].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)


In [161]:
x = np.arange(5)
print(x.shape)
print(x[:,np.newaxis].shape)
print(x[np.newaxis,:].shape)
print((x[:,np.newaxis]+ x[np.newaxis,:]).shape)

(5,)
(5, 1)
(1, 5)
(5, 5)


In [187]:
x = np.arange(10).reshape(2,5)
y = x > 2
print(y)

[[False False False  True  True]
 [ True  True  True  True  True]]


In [191]:
x = np.arange(35).reshape(5,7)
print(x)
x[np.array([0,2,4]), 1:3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [223]:
x = np.arange(0,50,10)
print(x)
x[np.array([1,1,3,1])] += 1
print(x)

[ 0 10 20 30 40]
[ 0 11 20 31 40]
